### ISSUE TITLE
Incorrect validation tooltip for `number` properties

### ISSUE THREAD

**Issue by ldamet** [dashjoin/json-schema-form#152]
Hello,

The form displays a validation error message in the tooltip on hover of a `number` property.
We can see that on the live demo page for instance:

![image](https://user-images.githubusercontent.com/1410076/188803829-de21bd81-885e-4e9d-aa70-e280b40c890b.png)

**Comment by aeberhart** [comment]
Thanks for catching this. The issue seems to be that we set the input type to number but do not specify a step property (which seems to default to 1). 

https://www.w3schools.com/tags/att_input_type_number.asp
https://stackoverflow.com/questions/48892570/please-enter-a-valid-value-the-two-nearest-valid-value-is

We can fix this by introducing a method getInputStep, similar to getInputType or alternatively by setting step to any by default. This would probably make the up/down arrows disappear.

**Comment by ldamet** [comment]
Thanks for the quick response.

I did a test using the `any` step and it fixes the tooltip issue. I still have the up/down arrow (they increment/decrement by 1).

Maybe offering the possibility to configure the step if people want to benefit from validation and precise increment/decrement could be a nice feature.

**Comment by aeberhart** [comment]
Excellent. Feel free to create a PR for this.
As for being able to configure this, it could look like this:

```
{
  "type": "number",
  "step": 0.1
}
```

I personally feel like a default of 1 is sufficient. Imagine you're entering a number 12.5 in 0.1 increments. That's a lot of clicks...

**Comment by ldamet** [comment]
I created a PR for the support of `step`. This is my first PR ever so please let me know If I need to change things or anything.
I didn't really find anywhere to document the `step` attribute.

**Comment by ldamet** [comment]
Great thank you! I didn't see the "multipleOf" applied to numbers, perfect use case.

Also thanks for this library :)
